site_visibility = {
    'All_Brands': False,
    'Appliance_Depot': True,
    'Appliance_Parts': True,
    'Automatic_Appliance': True,
    'Cashwell': True,
    'Coast_Parts': True,
    'DL_Parts_Co': True,
    'Dey_Parts': False,
    'Encompass': False,
    'Ereplacement_Parts': True,
    'Fox': False,
    'Genuine': False,
    'Guaranteed': True,
    'Ideal_Appliance': True,
    'Kitchen_Aid': True,
    'Marcone': False,
    'Part_Select': True,
    'Parts_Dr': True,
    'Parts_Simple': True,
    'Reliable': False,
    'Tribles': False,
    'UED': True,
    'VV_Appliance_Parts': False,
}
